app = 'waku-land'
primary_region = 'iad'

kill_signal = "SIGINT"
kill_timeout = 5

[[services]]
  auto_stop_machines=false
  auto_start_machines=true
  internal_port = 3000
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 4