name: CD

on:
  schedule:
    - cron: '0 */6 * * *'
  push:
    branches: [main]

jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Env
        run: |
          echo "${{ secrets.ENV }}" > .env
      - name: Install
        run: |
          pnpm install --frozen-lockfile
      - name: Build
        run: |
          pnpm run cd:build
      - name: Deploy Fly
        # load env vars, install deps, create fly.toml, and deploy
        run: |
          flyctl deploy --local-only -t "${{ secrets.FLY_ACCESS_TOKEN }}"
      - name: DNS
        run: |
          pnpm run cd:dns
